name: Reportify
version: '${project.version}'
main: me.goodbee.reportify.Reportify
api-version: '1.20'
commands:
  report:
    description: Report a player.
  z-respondreport:
    description: Internal response command.