name: Generate and Deploy Javadocs

on:
  push:
    branches:
      - main

jobs:
  generate-and-deploy-javadocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Javadocs
        run: |
          mvn javadoc:javadoc
          
      - name: Deploy Javadocs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: javadoc
          folder: /target/site/apidocs
